### ISSUE TITLE
hugeutils.c: 2 * poor error checking 

### ISSUE THREAD

**Issue by dcb314** [libhugetlbfs/libhugetlbfs#12]
1.

hugeutils.c:1170]: (style) Checking if unsigned variable 'ret' is less than zero.

Source code is

```
    if (ret < 0) {
        ERROR("Failed to read /proc/self/maps\n");
        return -1;
    }
```

but

```
size_t ret;
```

2.

hugeutils.c:1177]: (style) Checking if unsigned variable 'ret' is less than zero.

Duplicate.

**Comment by khers** [comment]
Patch for this issue: https://groups.google.com/d/msg/libhugetlbfs/NfKO-LIxNgo/nnNSG1lhAwAJ
