### ISSUE TITLE
--thp-khugepaged-alloc-sleep misspelled in hugeadm usage+man

### ISSUE THREAD

**Issue by Voltara** [libhugetlbfs/libhugetlbfs#34]
In the man page and usage output of hugeadm, the `--thp-khugepaged-alloc-sleep` option is misspelled as `--thp-khugepages-alloc-sleep` ("s" instead of "d").

https://github.com/libhugetlbfs/libhugetlbfs/blob/e44180072b796c0e28e53c4d01ef6279caaa2a99/hugeadm.c#L115

https://github.com/libhugetlbfs/libhugetlbfs/blob/e44180072b796c0e28e53c4d01ef6279caaa2a99/man/hugeadm.8#L269

**Comment by khers** [comment]
Fixed
