### ISSUE TITLE
huge_page_setup_helper.py Python3 conversion

### ISSUE THREAD

**Issue by aquini** [libhugetlbfs/libhugetlbfs#35]
As Python2 will soon become deprecated, script huge_page_setup_helper.py must be converted to Python3. Attached patch is the output of 2to3 Python conversion for that matter.

**Comment by aquini** [comment]
[huge_page_setup_helper-python3-convert.patch.txt](https://github.com/libhugetlbfs/libhugetlbfs/files/2168080/huge_page_setup_helper-python3-convert.patch.txt)

**Comment by harish-24** [comment]
Please let know if this will be taken care of anytime soon.

**Comment by khers** [comment]
As per the readme, please submit patches to the mailing list
