### ISSUE TITLE
shm-perms fails with "Page size is too large for configured SEGMENT_SIZE" on aarch64

### ISSUE THREAD

**Issue by aquini** [libhugetlbfs/libhugetlbfs#39]
Due to CONFIG_ARM64_64K_PAGES=y we get 512MB as default hugepage size, however the test sets the maximum size of a shmem segment (SHMMAX) too low: 64MB, causing this check to trip:
 80         check_hugetlb_shm_group();
 81         if (hpage_size > SEGMENT_SIZE)
 82                 CONFIG("Page size is too large for configured SEGMENT_SIZE\n");

The attached patch adjust the segment size to 1GB, so we don't fail with gigantic hugepages anymore.
[tests_shm-perms_adjust_max_segment_size_for_bigger_hugepages.patch.txt](https://github.com/libhugetlbfs/libhugetlbfs/files/2444660/tests_shm-perms_adjust_max_segment_size_for_bigger_hugepages.patch.txt)

**Comment by khers** [comment]
Please send patches to the mailing list
