### ISSUE TITLE
brk_new_huge failed when running with ./runtest -t func

### ISSUE THREAD

**Issue by ambrosehua** [libhugetlbfs/libhugetlbfs#53]
it turned out brk_new_huge failed when running test with ./runtest -t func

> root@localhost:/home/ambrosehua/projects/libhugetlbfs/tests# ./run_tests.py -t func
zero_filesize_segment (32M: 64):        PASS
test_root (32M: 64):    PASS
meminfo_nohuge (32M: 64):       PASS
gethugepagesize (32M: 64):      PASS
gethugepagesizes (32M: 64):     PASS
HUGETLB_VERBOSE=1 empty_mounts (32M: 64):       PASS
HUGETLB_VERBOSE=1 large_mounts (32M: 64):       PASS
find_path (32M: 64):    PASS
unlinked_fd (32M: 64):  PASS
readback (32M: 64):     PASS
truncate (32M: 64):     PASS
shared (32M: 64):       PASS
mprotect (32M: 64):     PASS
mlock (32M: 64):        PASS
misalign (32M: 64):     PASS
fallocate_basic.sh (32M: 64):   PASS
fallocate_align.sh (32M: 64):   PASS
ptrace-write-hugepage (32M: 64):        PASS
icache-hygiene (32M: 64):       PASS
slbpacaflush (32M: 64): PASS (inconclusive)
straddle_4GB_static (32M: 64):  PASS
huge_at_4GB_normal_below_static (32M: 64):      PASS
huge_below_4GB_normal_above_static (32M: 64):   PASS
map_high_truncate_2 (32M: 64):  PASS
misaligned_offset (32M: 64):    PASS (inconclusive)
truncate_above_4GB (32M: 64):   PASS
brk_near_huge (32M: 64):        brk_near_huge: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

but if running brk_near_huge directly, it passed

> root@localhost:/home/ambrosehua/projects/libhugetlbfs/tests# ./obj64/brk_near_huge
Starting testcase "./obj64/brk_near_huge", pid 15587
Initial break at 0xaabb54c000
Hugepage mapped at 0xaabe000000-0xaabfffffff
PASS

the failing is because the "test_addr_huge" trigger heap initialized, which made the chunk of malloc overwritten by later memset,
malloc from the PASS() oops

running it directly would turn on verbose,  which triggered malloc (test_init -> printf -> malloc) and made heap initialized before brk_new_huge lifted brk0, so memset would not touch the chunk of malloc

Is there any fix for this issue?

**Comment by sandip4n** [comment]
I have just posted a possible fix to the mailing list. Please have a look.
https://groups.google.com/forum/#!topic/libhugetlbfs/WCSvOt8UESg

**Comment by ambrosehua** [comment]
Nice work, thank you!

**Comment by ambrosehua** [comment]
fixed by https://groups.google.com/forum/#!topic/libhugetlbfs/WCSvOt8UESg
