### ISSUE TITLE
I have 2 segments overlap on 0x0-0x2000000，I think assignment layout area is a good idea.

### ISSUE THREAD

**Issue by buque** [libhugetlbfs/libhugetlbfs#59]
libhugetlbfs: INFO: Segment 0 (phdr 2): 0x200000-0x2008e0 (filesz=0x8e0) (prot = 0x5)
libhugetlbfs: INFO: Segment 1 (phdr 3): 0x5ffdd8-0x600040 (filesz=0x260) (prot = 0x3)
libhugetlbfs: WARNING: Layout problem with segments 0 and 1:
Segments would overlap

[root@openEuler common]# readelf -l test

Elf file type is EXEC (Executable file)
Entry point 0x2005c0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000200040 0x0000000000200040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000200238 0x0000000000200238
                 0x000000000000001b 0x000000000000001b  R      0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x0000000000000000 0x0000000000200000 0x0000000000200000
                 0x00000000000008e0 0x00000000000008e0  R E    0x200000
  LOAD           0x00000000001ffdd8 0x00000000005ffdd8 0x00000000005ffdd8

**Comment by Young-xin** [comment]
hi! how to fix the problem "Segments would overlap"? i used pagesize=1G,on x86_64
