### ISSUE TITLE
tmpfs does not support O_DIRECT

### ISSUE THREAD

**Issue by zhangyiru** [libhugetlbfs/libhugetlbfs#68]
![image](https://user-images.githubusercontent.com/15630061/138685356-ffd1b43d-eb1e-46aa-969a-916edb63cae6.png)
direct test is failed by bad configuration.

tmpfs does not support O_DIRECT in open manual
https://man7.org/linux/man-pages/man2/open.2.html

so i change the path of TMPFILE in direct.c, please review, thx~
#67

**Comment by luochenglcs** [comment]
From the error message, it is because the same file already exists.
