### ISSUE TITLE
Github's release tarball not useable - version.h:1:2: error: #error UNVERSIONED tarball

### ISSUE THREAD

**Issue by Whissi** [libhugetlbfs/libhugetlbfs#7]
Hi,

when you try building from the latest release tarball (https://github.com/libhugetlbfs/libhugetlbfs/archive/2.20.tar.gz) you will end up with an error like
```
In file included from version.c:1:0:
version.h:1:2: error: #error UNVERSIONED tarball
 #error UNVERSIONED tarball
  ^
version.c:3:55: error: expected ‘,’ or ‘;’ before ‘VERSION’
 static const char libhugetlbfs_version[] = "VERSION: "VERSION;
                                                       ^
Makefile:294: recipe for target 'obj64/version.o' failed
In file included from elflink.c:42:0:
version.h:1:2: error: #error UNVERSIONED tarball
 #error UNVERSIONED tarball
  ^
make: *** [obj64/version.o] Error 1
make: *** Waiting for unfinished jobs....
```
When you compare the GitHub release tarball with the 2.19 release tarball from [SF](https://sourceforge.net/projects/libhugetlbfs/files/latest/download) you will notice that that SF release tarball contains a "version" file...

**Comment by khers** [comment]
The tar balls for sourceforge were generated with the mktarball script which creates the version file and adds it to the tar ball before compressing.  I am not keen on keeping a version file checked in (and the one that is created with the script is more useful than just the last version released).  All I can think to do here is to update the libhugetlbfs docs to mention this.

**Comment by vapier** [comment]
github's release system makes it trivial to attach generated tarballs to a tag too for people to fetch.

expecting people to manually write the version to the unpacked tarball is unreasonable, and putting it in the docs doesn't really help.

**Comment by khers** [comment]
I never suggested people manually write a version file.

Having to edit a tag to add a binary attachment is not intuitive, but releases 2.18, 2.19, and 2.20 should now have working tar balls attached to them.
