### ISSUE TITLE
Does the project are still maintained?

### ISSUE THREAD

**Issue by zhangwenlong8911** [libhugetlbfs/libhugetlbfs#71]
hello
    Does the project are still maintained?I have sent a patch mail for libhugetlbfs@googlegroups.com, and no one reply.Is the email address changed?

**Comment by mjkravetz** [comment]
That is a good question.  I think deprecation of morecore in glibc may be an issue to kill this project.

**Comment by NicholasLindsay** [comment]
See https://github.com/libhugetlbfs/libhugetlbfs/issues/52 for more discussion on the deprecation of morecore and the impact on libhugetlbfs.

**Comment by luochenglcs** [comment]
Although glibc has deprecated morecore, which impacts libhugetlbfs, it is still maintained because it continues to have great value.

**Comment by luochenglcs** [comment]
Although glibc has deprecated morecore with impact on libhugetlbfs, but  it is still maintained as it still has great value.
